### ISSUE TITLE
[Feature Request] Layout Viewer fields sorting

### ISSUE THREAD

**Issue by IceCone-Topy** [CyberAgentGameEntertainment/SmartAddresser#39]
When i have lots of versions and asset groups, it's difficult to check is all asset set to right version and labels.

If can sort by Group name, labels and version will be great

An example to show how do i need sort feature
![image](https://github.com/CyberAgentGameEntertainment/SmartAddresser/assets/79889802/aaca5954-86c9-4881-936e-5690e0fd2a70)

**Comment by Haruma-K** [comment]
Thank you for the suggestion!
Indeed, I think it would be better to implement such a feature. I will consider it, so please give me some time.

**Comment by IceCone-Topy** [comment]
Search feature is working now.
I can use that for now.
No rush.

**Comment by Haruma-K** [comment]
Released as 1.0.3.
Thank you for your idea!

https://github.com/CyberAgentGameEntertainment/SmartAddresser/releases/tag/1.0.3
