### ISSUE TITLE
[Bug] Exclude Unversioned check box not display correctly

### ISSUE THREAD

**Issue by abcde134256** [CyberAgentGameEntertainment/SmartAddresser#42]
In this picture the `Exclude Unversioned` check box is uncheck, but in Inspector is checked.

Inpector is right, Layout Rule Editor is wrong.

![image](https://github.com/CyberAgentGameEntertainment/SmartAddresser/assets/10219519/2aa2007f-1a42-44fe-a3bb-e447ee1d1955)

**Comment by Haruma-K** [comment]
Sorry for the late reply. I've checked, but I counld not reproduce the issue you mentioned. I would appreciate it if you could provide me with the steps to reproduce the problem.
