### ISSUE TITLE
[Feature Request] Need Extension Version

### ISSUE THREAD

**Issue by abcde134256** [CyberAgentGameEntertainment/SmartAddresser#43]
Now the version is use Semantic Versioning
But Semantic Versioning is use to App

So asset maybe not suit to this rule

Here is my thought, i want to asset version relate to app version
so if app version is 1.2.3, then asset version will start in 1.2.3.0, first three number will sync to app version, and if asset need to update but in same app version, change the 4th number

But now this tool use `IVersionExpressionParser` and it use `CompositeVersionComparator` class that use `Version` class, so i can't implement my version rule

Or is there has another way to do this?

**Comment by Haruma-K** [comment]
I believe what you're trying to achieve can likely be accomplished using Semantic Versioning's Pre-release versions or build metadata.

https://semver.org/

Smart Addresser also supports this. Test is here.

https://github.com/CyberAgentGameEntertainment/SmartAddresser/blob/main/Assets/SmartAddresser/Tests/Editor/Foundation/SemanticVersioning/PrereleaseComparisonTest.cs
