### ISSUE TITLE
[Bug] ObjectFilterにフォルダを指定した時に同じ名前を含む他のフォルダも対象になる

### ISSUE THREAD

**Issue by Rapilias** [CyberAgentGameEntertainment/SmartAddresser#44]
## 概要
LayoutRuleEditorのObjectFilterにフォルダを指定する際、同一階層にある対象のフォルダ名を含む別のフォルダも対象になってしまいます。
以下は`GroupA`という文字列を含む独立したグループが同一のグループ扱いされてしまう例です。
![ce8f1519-b5b2-449c-93af-135c997bb48a](https://github.com/CyberAgentGameEntertainment/SmartAddresser/assets/91034223/e11b0cc9-1f41-41a9-baeb-6e87ccb4218d)

## 予期される動作
ObjectFilterに`GroupA`を指定した時`GroupA`フォルダ以下だけが対象になる

## 実際の動作
ObjectFilterに`GroupA`を指定した時同階層にある`GroupA`で始まる文字列を含むフォルダ以下が対象になる

## 環境
OS: Windows11
Unity: 2020.3.40f1, 2023.2.3f1

## その他
Fork先の https://github.com/Rapilias/SmartAddresser/pull/3 にて修正しました。
予期される動作が意図通りであれば、こちらにもPRを出そうと思います。

**Comment by Haruma-K** [comment]
@Rapilias 
ご指摘ありがとうございます。
こちらいただいた通りの事象とコードの不具合を確認しました。

修正内容も確認しましたので、ぜひPRを出していただきたいです。
ご指摘大変助かります、テストまでありがとうございます！

**Comment by Haruma-K** [comment]
v1.0.4でリリースしました！

https://github.com/CyberAgentGameEntertainment/SmartAddresser/releases/tag/1.0.4
