### ISSUE TITLE
[Feature Request] アセット選択時にProjectウインドウの対応するアセットを選択する

### ISSUE THREAD

**Issue by Rapilias** [CyberAgentGameEntertainment/SmartAddresser#47]
## 概要
Addressables Groups ウインドウと同様に、ファイル選択時に選択したアセットをProject WindowとInspectorに表示できると便利です。
また、https://github.com/CyberAgentGameEntertainment/SmartAddresser/issues/46 を回避するため、Addressables Groups ウインドウを表示せずに対象のアセットに飛びたい という意図もあります。

**Comment by Haruma-K** [comment]
ありがとうございます。PRをマージさせていただきました。
