### ISSUE TITLE
Unnecessary Changes may appear when execute "Apply to Addressables" from Layout Rule Editor

### ISSUE THREAD

**Issue by shunsuke-saito-mummy** [CyberAgentGameEntertainment/SmartAddresser#49]
## Gratitude
I'd like to extend my gratitude for the development of this invaluable library.

## Issue Description
I have encountered an issue when using "Apply to Addressables" from the Layout Rule Editor to assign addresses based on rules.
It appears that the order of the operation is contingent upon the sequence of the asset paths returned by `AssetDatabase.GetAllAssetPaths`.
Consequently, this reliance leads to a scenario where changes are reflected in the Addressable Asset Groups post address assignment even when no actual changes have been made to the assets themselves.

**Comment by Haruma-K** [comment]
v1.0.5でリリースしました、ありがとうございました！

https://github.com/CyberAgentGameEntertainment/SmartAddresser/releases/tag/1.0.5
