### ISSUE TITLE
[Bug] Breaking the Addressables settings automatically assigned to Unity Localization artifacts.

### ISSUE THREAD

**Issue by ymizuno-sun** [CyberAgentGameEntertainment/SmartAddresser#53]
When applying rules with existing files generated by Unity Localization, it may disrupt the Localization settings.

**Comment by Haruma-K** [comment]
The Unity Localization tool registers its own addresses, so it should not be controlled by Smart Addresser.

**Comment by ymizuno-sun** [comment]
Apologies for the confusion. The issue is that it disrupts the settings even without applying the control options correctly.

![image](https://github.com/CyberAgentGameEntertainment/SmartAddresser/assets/152393117/458c0ea7-a476-4f81-a7a1-da633805e590)

I cannot check the 'Control' option as shown in the attached image.

**Comment by ymizuno-sun** [comment]
@Haruma-K 
![Animation](https://github.com/CyberAgentGameEntertainment/SmartAddresser/assets/152393117/b4ca7316-ac7b-42da-88d7-d61a4d8c8d05)

**Comment by Haruma-K** [comment]
Got it, that seems odd. I'll check it out later, so please wait.

**Comment by Haruma-K** [comment]
probably this commit is the cause

https://github.com/CyberAgentGameEntertainment/SmartAddresser/commit/79a306f47b460085cb131582809a49eca9fe1eff

**Comment by Haruma-K** [comment]
PR: https://github.com/CyberAgentGameEntertainment/SmartAddresser/pull/54 (under review)

**Comment by Haruma-K** [comment]
Released in 1.0.6.
https://github.com/CyberAgentGameEntertainment/SmartAddresser/releases/tag/1.0.6

Thanks for your report!
