### ISSUE TITLE
Unity Editor crashes when calling ApplyRules() method in OnPreprocessBuild.

### ISSUE THREAD

**Issue by felixngd** [CyberAgentGameEntertainment/SmartAddresser#57]
- Unity 2022.3.20f1
- Smart Addresser 1.0.7
- Addressables 1.21.21

**Comment by Haruma-K** [comment]
@felixngd 

Thank you for your report.

It seems like you might be calling the wrong method. That method is intended for execution via the CLI.
To run it from the Unity Editor, please refer to the following documentation.

https://github.com/CyberAgentGameEntertainment/SmartAddresser/blob/1e49e1b4369b27460afa7317ade7b300e4ab0b7c/README.md#validation-and-apply-to-addressable-asset-system

**Comment by felixngd** [comment]
Thanks for your feedback, it works!
